spring:
   application:
      name: restaurant-gateway-service
#  profiles:
#    active: dev
spring:
  cloud:
    gateway:
      routes:
      - id: default_route
        uri: https://cloud.spring.io/spring-cloud-gateway
        predicates:
        - Path=/cloud/



server:
  port: 8989