#spring:
#  profiles:
#    active: dev
spring:
  cloud:
    gateway:
      routes:
      -id: create_route
      uri: http://localhost:8080/games
      predicate:
      - Path=/games/



server:
  port: 8989