#spring:
#  profiles:
#    active: dev
spring:
  cloud:
    gateway:
      routes:
      - id: default_route
        uri: http://localhost:8080/games/default
        predicates:
        - Path=/games/



server:
  port: 8989